pipeline {
  agent any
  tools { 
        maven 'Maven_3_5_2'  
    }
   stages{
    stage('CompileandRunSonarAnalysis') {
            steps {	
		withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
			sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=apotiwebapp -Dsonar.organization=apotiwebapp -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN'
		}
			}
        } 
  }
}
