version: 0.2

env:
  parameter-store:
    USERNAME: /myapp/docker-credentials/username
    PASSWORD: /myapp/docker-credentials/password
    KEY:  /myapp/api/key

        
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "installed node "
    # steps:
  pre_build:
    commands:
      - npm install
      - echo "dependencies installed"
  build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker build . -t dhruvdarji123/netflix-react-app:$IMAGE_TAG --build-arg TMDB_V3_API_KEY=$KEY
  post_build:
    commands:
      - echo "Scanning Image with Trivy"
      - trivy image --exit-code 1 --severity HIGH,CRITICAL dhruvdarji123/netflix-react-app:$IMAGE_TAG
      - echo "Logging into DockerHub"
      - docker login -u $USERNAME -p $PASSWORD
      - docker push dhruvdarji123/netflix-react-app:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: build-artifact-name
  discard-paths: no
