pipeline {
  agent any
  tools { 
        maven 'Maven_3_5_2'  
    }
   stages{
    stage('CompileandRunSonarAnalysis') {
            steps {	
		sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=apotiwebapp -Dsonar.organization=apotiwebapp -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=66f356140208764dfe69d59ed877df284c86c585'
			}
    }

	stage('RunSCAAnalysisUsingSnyk') {
            steps {		
				withCredentials([string(credentialsId: 'SNYK_TOKEN', variable: 'SNYK_TOKEN')]) {
					sh 'mvn snyk:test -fn'
				}
			}
    }

	stage('Build') { 
            steps { 
               withDockerRegistry([credentialsId: "dockerlogin", url: ""]) {
                 script{
                 app =  docker.build("<IMAGE_NAME>")
                 }
               }
            }
    }

	stage('Push') {
            steps {
                script{
# Replace <AWS_ACCOUNT_ID> with your AWS account ID
                    docker.withRegistry('https://<AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com', 'ecr:us-west-2:aws-credentials') {
                    app.push("latest")
                    }
                }
            }
    	}
	    
  }
}
