apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
  namespace: gitops-demo
  labels:
    app: hello-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gitops
  template:
    metadata:
      labels:
        app: hello-gitops
    spec:
      containers:
        - name: app
          image: nginxdemos/hello:0.4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

